### ISSUE TITLE
Confusing derivation path for BRD, Multibit and Hodlwallet

### ISSUE THREAD

**Issue by maxtannahill** [nvk/wallets-recovery#30]
In the Ian Coleman tool, a derivation path of m/0'/0 is required in the BIP32 Derivation Path field but in Electrum, a m/0′ derivation path is used.

Users need to be clear which path to use if they are going to recover their wallets correctly. 

"BIP32 non 44 Compatible" is still not clear enough.

**Comment by nvk** [comment]
Want to make a PR with better language? Needs to fit. Or add notation and more info at the bottom.

**Comment by maxtannahill** [comment]
Yes, eventually. I firstly need to understand what the correct notation is. The two paths don't seem interchangeable.

**Comment by nvk** [comment]
BRD fixes.

**Comment by hosiawak** [comment]
I suggest using the base derivation path that Electrum expects because Electrum is most likely the tool that will be used to recover all these wallets.
