### ISSUE TITLE
Copay?

### ISSUE THREAD

**Issue by Transisto** [nvk/wallets-recovery#35]

**Comment by nvk** [comment]
Do they even support bitcoin these days? If so, add to the list.

**Comment by hosiawak** [comment]
Here's some info https://github.com/bitpay/copay/issues/3930

It would be good to verify the base derivation path, there seems to be multiple depending on the version used. I haven't used it so can't verify.

**Comment by maxtannahill** [comment]
Better links [here](https://bitpay.github.io/copay-recovery/) and [here](https://github.com/bitpay/copay#wallet-export-format). I will do a PR when I can work out how to do the next one.

**Comment by maxtannahill** [comment]
Merged, can be closed.
