### ISSUE TITLE
Add passphrase column

### ISSUE THREAD

**Issue by maxtannahill** [nvk/wallets-recovery#41]
Thoughts for this? For Samourai and Wasabi, the passphrase is mandatory. If this isn't supported on other wallets, it should be highlighted.

**Comment by yahiheb** [comment]
For Wasabi the passphrase is not mandatory.

**Comment by maxtannahill** [comment]
Mandatory but can be empty as [here](https://github.com/zkSNACKs/WalletWasabi/issues/1308)
