### ISSUE TITLE
Bottom table not rendering correctly

### ISSUE THREAD

**Issue by maxtannahill** [nvk/wallets-recovery#77]
It looks fine on the readme.md on Github 

<img width="1006" alt="Screenshot 2019-08-31 at 13 21 20" src="https://user-images.githubusercontent.com/13302849/64059617-837c5b00-cbf2-11e9-97a9-829e2ab9e794.png">

...but on the walletsrecovery.org page, it isn't rendering. Same for mobile too.

<img width="1000" alt="Screenshot 2019-08-31 at 13 20 51" src="https://user-images.githubusercontent.com/13302849/64059613-7fe8d400-cbf2-11e9-88ba-d43560119480.png">

**Comment by nvk** [comment]
Fixed
