### ISSUE TITLE
Enforce HTTPS for walletsrecovery.org

### ISSUE THREAD

**Issue by ericallam** [nvk/wallets-recovery#8]
Github Pages has an option for forcing HTTPS which will redirect clients that request http://walletsrecovery.org to https://walletsrecovery.org. See more [here](https://github.blog/2018-05-01-github-pages-custom-domains-https/). 

This prevents walletsrecovery.org from being trivially MITM'ed, which would allow an attacker to provide incorrect wallet recovery information which may give them access to a user's seed.

**Comment by nvk** [comment]
It's on the list of things to todo.

**Comment by nvk** [comment]
done.
