### ISSUE TITLE
Update BitBox Info

### ISSUE THREAD

**Issue by jstrnbrg** [nvk/wallets-recovery#87]
Hi, could you please update the following rows, thanks.

## BitBox01: 
Derivation: m/44'|49'|84'/0'/0' 
BIP-39 Pass: required
PSBT: not supported
Docs: https://guides.shiftcrypto.ch/docs/BitBox01

## BitBox02: 
Derivation: m/44'|49'|84'/0'/0'
BIP-39 Pass: optional
PSBT: not supported
Docs: https://guides.shiftcrypto.ch/docs/BitBox02

**Comment by nvk** [comment]
Will do, what's the deep link to the external recovery process?

**Comment by jstrnbrg** [comment]
Thanks :)
In the guides: https://guides.shiftcrypto.ch/docs/bitbox01/Other/bitbox01_backup/
On Github (to run offline): https://github.com/digitalbitbox/html_backup

**Comment by jstrnbrg** [comment]
Any update on when the page will get updated? Thanks @nvk

**Comment by jstrnbrg** [comment]
Hi Novak, 

unfortunately all these urls changed, here are the new links. Pls update, thanks :) 

## BitBox01:
Derivation: m/44'|49'|84'/0'/0'
BIP-39 Pass: required
PSBT: not supported
Docs: https://guides.shiftcrypto.ch/bitbox01/

##BitBox02:
Derivation: m/44'|49'|84'/0'/0'
BIP-39 Pass: optional
PSBT: not supported
Docs: https://guides.shiftcrypto.ch/bitbox02/
