### ISSUE TITLE
Recover Electrum wallet in other wallets (e.g. Wasabi Wallet)

### ISSUE THREAD

**Issue by yahiheb** [nvk/wallets-recovery#89]
I have been trying to restore electrum wallet in Wasabi but I did not succeed.
What are all the information needed to do that.

**Comment by maxtannahill** [comment]
Are you trying this with a Electrum created BIP39 wallet and passphrase with m/84’ derivation path before trying this on Wasabi?

**Comment by yahiheb** [comment]
`Electrum does not generate BIP39 seeds` [source](https://electrum.readthedocs.io/en/latest/seedphrase.html)
I was creating a simple segwit wallet on Electrum then tried to recover it using Wasabi.
I think Electrum's seed mnemonic is not compatible with other wallet software.

**Comment by maxtannahill** [comment]
Yes, Electrum seeds are not compatible with any other wallets from what I can see although they support import of BIP39 seeds.

**Comment by yahiheb** [comment]
Maybe we should mention that Electrum seed phrases are not compatible with any other wallets.

**Comment by maxtannahill** [comment]
Agree. We have mentioned that the client itself supports BIP39 but it’s worth highlighting to the user the risk of using Electrum seeds if it is the only implementation around. I will investigate to see if there are any other wallets that support it before updating the matrix.

**Comment by nvk** [comment]
https://github.com/nvk/wallets-recovery/issues/132 clarifies this.
