### ISSUE TITLE
Add WIF support 

### ISSUE THREAD

**Issue by nvk** [nvk/wallets-recovery#96]
- SW https://twitter.com/samouraidev/status/1193514580816871427?s=21
- green, Coinomi, mycelium 
- fullynoded https://twitter.com/fullynoded/status/1193525236689321984?s=21

**Comment by Enegnei** [comment]
Added 'Yes' for Samourai, Blockstream Green, Coinomi, and Mycelium. Added a new row for [FullyNoded](https://github.com/Fonta1n3/FullyNoded) since it did not have one yet; will need its various columns filled. https://github.com/nvk/wallets-recovery/commit/f1a92e93a292ed5da4e9476b91acfed419ce9e8d
